config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    root "application#index"

    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end
  end

  devise_for :users
  root "projects#index"
  resources :projects, only: [:index, :show, :edit, :update] do 
    resources :tickets
  end

  resources :attachments, only: [:show, :new]
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :author, class_name: "User"
  has_many :attachments, dependent: :destroy

  accepts_nested_attributes_for :attachments, reject_if: :all_blank

  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 10 }

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_project
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def new
    @ticket = @project.tickets.build
    authorize @ticket, :create?
    3.times { @ticket.attachments.build }
  end

  def create
    @ticket = @project.tickets.build(ticket_params)
    @ticket.author = current_user
    authorize @ticket, :create?
    if @ticket.save
      flash[:notice] = "Ticket has been created."
      redirect_to [@project, @ticket]
    else
      flash.now[:alert] = "Ticket has not been created."
      render "new"
    end
  end

  def show
    authorize @ticket, :show?
  end

  def edit
    authorize @ticket, :update?
  end

  def update
    authorize @ticket, :update?
    if @ticket.update(ticket_params)
      flash[:notice] = "Ticket has been updated."
      redirect_to [@project, @ticket]
    else
      flash.now[:alert] = "Ticket has not been updated."
      render "edit"
    end
  end

  def destroy
    authorize @ticket, :destroy?
    @ticket.destroy
    flash[:notice] = "Ticket has been deleted."

    redirect_to @project
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_ticket
    @ticket = @project.tickets.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:name, :description, attachments_attributes: [:file, :file_cache])
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= simple_form_for([@project, @ticket]) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <div id="attachments">
    <h3>Attachments</h3>
    <%= render partial: "attachments/form", locals: { f: f, index: 0 } %>
  </div>
  <p>
    <%= link_to "Add another file", new_attachment_path, remote: true, id: "add_file", 
    data: { params: {index: ticket.attachments.size} } %>
  </p>

  <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/tickets/edit.html.erb
<header>
  <h1>
    Edit Ticket
    <small><%= @project.name %></small>
  </h1>
</header>
  <%= render "tickets/form" %>

app/views/tickets/new.html.erb
<header>
  <h1>
    New Ticket
    <small><%= @project.name %></small>
  </h1>
</header>
  <%= render "tickets/form" %>

app/views/tickets/show.html.erb
<div id="ticket">
  <header>
    <h1><%= @project.name %></h1>
  </header>

  <header>
    <h2><%= @ticket.name %></h2>

    <ul class="actions">
      <% if policy(@ticket).update? %>
        <li><%= link_to "Edit Ticket", [:edit, @project, @ticket],
          class: "edit" %></li>
      <% end %>
      <% if policy(@ticket).destroy? %>
        <li><%= link_to "Delete Ticket", [@project, @ticket],
          method: :delete,
          data: { confirm: "Are you sure you want to delete this ticket?" },
          class: "delete" %></li>
      <% end %>
    </ul>
  </header>

  <%= simple_format(@ticket.description) %>

  <% if @ticket.attachments.any? %>
    <h4>Attachments</h4>
    <div class="attachments">
      <% @ticket.attachments.each do |attachment| %>
        <p>
          <%= link_to File.basename(attachment.file.url),
            attachment_path(attachment) %>
          (<%= number_to_human_size(attachment.file.size) %>)
        </p>
      <% end %>
    </div>
  <% end %>

  <table id="attributes">
   <tr>
     <th>Author:</th>
     <td><%= @ticket.author.email %></td>
   </tr>
   <tr>
     <th>Created:</th>
     <td><%= time_ago_in_words(@ticket.created_at) %> ago</td>
   </tr>
</table>
</div>